server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.154.1
    username: huawei
    password: huawei
    virtual-host: /huawei-shop
huawei:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 微服务商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称