server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.154.1 #localhost
    username: huawei
    password: huawei
    virtual-host: /huawei-shop
  redis:
    host: 192.168.75.129
huawei:
  sms:
    accessKeyId: LTAIKiGbhMtZTWEJ # 你自己的accessKeyId
    accessKeySecret: yr8gZZTOWfZarKMmRfIg5lnckBsxSy # 你自己的AccessKeySecret
    signName: 华为微服务商城 # 签名名称
    verifyCodeTemplate: SMS_167396013 # 模板名称