server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.75.131:3306/huawei_shop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: cf703861
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.75.129
  rabbitmq:
    host: 192.168.154.1
    username: huawei
    password: huawei
    virtual-host: /huawei-shop
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: huawei.cart.exchange
    publisher-confirms: true
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.huawei.order.pojo
huawei:
  jwt:
    pubKeyPath: D:/localFile/rsa.pub # 公钥地址
    cookieName: HUAWEI_SHOP_TOKEN #cookie名称
  worker:
    workerId: 1
    datacenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl:  http://dji63k.natappfree.cc/wxpay/notify


